on:
  pull_request:
    paths:
      - '**/action.yml'
      - '**/action.yaml'
      - '**/.github/workflows/*.yml'
      - '**/.github/workflows/*.yaml'

name: Check YAML

jobs:
  check-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pl-strflt/validate-yaml-schema@030046537f7f801a88c0cd7afd43c7b1d67cf74b
        with:
          yamlSchemasJson: |
            {
              "https://json.schemastore.org/github-action.json": ["**/action.yml", "**/action.yaml"],
              "https://json.schemastore.org/github-workflow.json": ["**/.github/workflows/*.yml", "**/.github/workflows/*.yaml"]
            }
